mutation addEmployee($name: String!, $pin: Int!, $sheet_id: String!) {
  insert_Employee(objects: { name: $name, pin: $pin, sheet_id: $sheet_id}) {
    returning {
      name
      pin
      sheet_id
    }
  }
}
